---

- name: Add OpenLDAP system user to additional groups
  user:
    name: 'openldap'
    groups: '{{ slapd_append_groups | join(",") | default(omit) }}'
    append: True
    state: 'present'
  notify: [ 'Restart slapd' ]
  when: slapd_pki|d() and slapd_pki | bool

- name: Check if TLS certificate is configured
  shell: ldapsearch -LLL -Y EXTERNAL -H ldapi:/// -b cn=config -s base 'olcTLSCertificateFile=*' olcTLSCertificateFile
  register: slapd_register_tls_cert_search
  changed_when: False

- name: Create random temporary directory for ldif file
  tempfile:
    state: 'directory'
  register: slapd_register_tempdir
  when: slapd_pki|d() and slapd_pki | bool and
        not (slapd_register_tls_cert_search.stdout is search("olcTLSCertificateFile:"))

- name: Prepare temporary ldif file
  template:
    src: 'tmp/configure_tlscerts.ldif.j2'
    dest: '{{ slapd_register_tempdir.path|d() + "/configure_tlscerts.ldif" }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: slapd_pki|d() and slapd_pki | bool and
        not (slapd_register_tls_cert_search.stdout is search("olcTLSCertificateFile:"))

- name: Restart slapd (first time only)
  service:
    name: 'slapd'
    state: 'restarted'
  when: slapd_pki|d() and slapd_pki | bool and
        not (slapd_register_tls_cert_search.stdout is search("olcTLSCertificateFile:"))

  # The private key and X.509 certificate entries need to be added at the same
  # time, otherwise the LDAP server errors out during configuration reload
  # performed on each OCI change. Ref: https://github.com/ansible/ansible/issues/25665
- name: Configure TLS certificates (first time only)
  command: 'ldapmodify -v -Y EXTERNAL -H ldapi:/// -f {{ slapd_register_tempdir.path|d() + "/configure_tlscerts.ldif" }}'
  register: slapd__register_tls_init
  when: slapd_pki|d() and slapd_pki | bool and
        not (slapd_register_tls_cert_search.stdout is search("olcTLSCertificateFile:"))
  failed_when: (("replace olcTLSCertificateFile:" not in slapd__register_tls_init.stdout_lines and
                 "replace olcTLSCertificateKeyFile:" not in slapd__register_tls_init.stdout_lines) or
                slapd__register_tls_init.rc != 0)

- name: Configure TLS ciphers and Diffie-Hellman params
  ldap_attr:
    dn: 'cn=config'
    name: '{{ item.key }}'
    values: '{{ item.value }}'
    state: 'exact'
  with_dict:
    olcTLSDHParamFile:        '{{ slapd_dhparam_file }}'
    olcTLSCipherSuite:        '{{ slapd_pki_ciphers }}'
  when: slapd_pki|d() and slapd_pki | bool and item.value|d()
