---

dependencies:

  - role: debops.ansible_plugins

galaxy_info:

  role_name: 'grafana'
  author: 'Bechea Leonardo, Alin Alexandru'
  description: 'Install and manage Grafana Dashboard'
  company: 'DebOps'
  license: 'GPL-3.0-only'
  min_ansible_version: '2.6'
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - utopic
        - vivid
    - name: Debian
      versions:
        - jessie
        - wheezy
  galaxy_tags:
    - grafana
