---

dependencies:

  - role: debops.ansible_plugins

galaxy_info:

  role_name: 'haproxy'
  author: 'Bechea Leonardo, Alin Alexandru'
  description: 'Install and manage Haproxy service'
  company: 'DebOps'
  license: 'GPL-3.0-only'
  min_ansible_version: '1.2'
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - precise
        - xenial
        - bionic
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
        - bullseye
  galaxy_tags:
    - haproxy
