---

dependencies:

  - role: debops.secret

galaxy_info:

  role_name: 'influxdb'
  author: 'Bechea Leonardo'
  description: 'Configure InfluxDB APT repositories'
  company: 'DebOps'
  license: 'GPL-3.0-only'
  min_ansible_version: '2.2.0'
  platforms:
    - name: Ubuntu
      versions:
        - xenial
    - name: Debian
      versions:
        - jessie
        - stretch
  galaxy_tags:
    - influxdb
