---

dependencies:

  - role: debops.secret
  - role: debops.ansible_plugins

galaxy_info:

  role_name: 'influxdb'
  author: 'Bechea Leonardo, Alin Alexandru'
  description: 'Install and manage InfluxDB service'
  company: 'DebOps'
  license: 'GPL-3.0-only'
  min_ansible_version: '2.8'
  platforms:
    - name: Ubuntu
      versions:
        - xenial
    - name: Debian
      versions:
        - jessie
        - stretch
  galaxy_tags:
    - influxdb
