---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# debops.jenkins default variables
# ================================

# .. contents:: Sections
#    :local:
#
# .. include:: ../../../../includes/global.rst

# Installation, APT packages [[[
# ------------------------------

# .. envvar:: jenkins__upstream_apt_id [[[
#
# The URL of the upstream Jenkins GPG key.
jenkins__upstream_apt_id: '150F DE3F 7787 E7D1 1EF4  E12A 9B7D 32F2 D505 82E6'
                                                                   # ]]]
# .. envvar:: jenkins__upstream_apt_url [[[
#
# The URL of the upstream Jenkins GPG key.
jenkins__upstream_apt_url: 'https://pkg.jenkins.io/debian-stable/jenkins.io.key'
                                                                   # ]]]
# .. envvar:: jenkins__upstream_apt_repository [[[
#
# The APT repository URI of the upstream Jenkins repository.
jenkins__upstream_apt_repository: 'deb https://pkg.jenkins.io/debian-stable binary/'
                                                                   # ]]]
# .. envvar:: jenkins__base_packages [[[
#
# List of APT packages to install for Jenkins support.
jenkins__base_packages:
  - 'jenkins'
                                                                   # ]]]
# .. envvar:: jenkins__packages [[[
#
# List of additional APT packages to install with Jenkins.
jenkins__packages: []
                                                                   # ]]]
# Configuration for other Ansible roles [[[
# -----------------------------------------

# .. envvar:: jenkins__keyring__dependent_apt_keys [[[
#
# Configuration for the :ref:`debops.keyring` Ansible role.
jenkins__keyring__dependent_apt_keys:

  - id: '{{ jenkins__upstream_apt_id }}'
    url: '{{ jenkins__upstream_apt_url }}'
    repo: '{{ jenkins__upstream_apt_repository }}'

                                                                   # ]]]
# Firewall
# Nginx
                                                                   # ]]]
