---

- name: Manage Influx APT repositories
  hosts: [ 'debops_service_influxdata', 'debops_influxdata' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences', 'skip::apt_preferences' ]
      apt_preferences__dependent_list:
        - '{{ influxdata__apt_preferences__dependent_list }}'

    - role: debops.influxdata
      tags: [ 'role::influxdata', 'skip::influxdata' ]
