---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# debops.infludata default variables [[[
# ====================================

# .. contents:: Sections
#    :local:
#
# .. include:: ../../../includes/global.rst


# Infludata server configuration [[[
# --------------------------------

# APT packages [[[
# ----------------

# .. envvar:: infludata__base_packages [[[
#
# List of base APT packages to install
influxdata__base_packages: []

                                                                   # ]]]
# .. envvar:: influxdata__packages [[[
#
# List of APT packages to install on all hosts in Ansible inventory.
influxdata__packages: []

                                                                   # ]]]
# .. envvar:: influxdatag__group_packages [[[
#
# List of APT packages to install on a group of hosts in Ansible inventory.
influxdata__group_packages: []

                                                                   # ]]]
# .. envvar:: influxdata__host_packages [[[
#
# List of APT packages to install on specific hosts in Ansible inventory.
influxdata__host_packages: []

                                                                   # ]]]
# .. envvar:: influxdata__dependent_packages [[[
#
# List of APT packages to install specified by other Ansible roles.
influxdata__dependent_packages: []
                                                                   # ]]]
                                                                   # ]]]
# .. envvar:: influxdata__upstream_key [[[
#
# The key used to sign the :command:`yadm` releases.
influxdata__upstream_key: 'https://repos.influxdata.com/influxdb.key'

                                                                   # ]]]
# .. envvar:: influxdata__upstream_repo [[[
#
# The URL of the infkuxdata upstream :command:`git` repository.
influxdata__upstream_repo: 'deb https://repos.influxdata.com/ubuntu bionic stable'

                                                                   # ]]]
influxdata__upstream_enabled: '{{ True
                                if (ansible_distribution_release in
                                    [ "jessie", "stretch", "trusty", "xenial" ])
                                else influxdata__dependent_upstream_enabled }}'
influxdata__dependent_upstream_enabled: False