---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# debops.influxdb default variables
# =================================

# .. contents:: Sections
#    :local:
#
# .. include:: ../../../../includes/global.rst


# InfluxDB server configuration [[[
# --------------------------------

# APT packages [[[
# ----------------

# .. envvar:: influxdb__base_packages [[[
#
# List of APT base packages which are required by the InfluxDB application.
influxdb__base_packages: [ 'influxdb' ]

                                                                   # ]]]
# .. envvar:: influxdb__packages [[[
#
# List of APT packages which are required by the InfluxDB application.
influxdb__packages: [ 'influxdb-dev' ]

                                                                   # ]]]
# .. envvar:: influxdb__group_packages [[[
#
# List of APT packages to install on a group of hosts in InfluxDB inventory.
influxdb__group_packages: []

                                                                   # ]]]
# .. envvar:: influxdb__host_packages [[[
#
# List of APT packages to install on specific hosts in InfluxDB inventory.
influxdb__host_packages: []

                                                                   # ]]]
# .. envvar:: influxdb__dependent_packages [[[
#
# List of APT packages to install specified by other InfluxDB roles.
influxdb__dependent_packages: []
                                                                   # ]]]
                                                                   # ]]]
# .. envvar:: influxdb__upstream_apt_key [[[
#
# The InfluxDB key of the Influxdb upstream APT repository.
influxdb__upstream_apt_key: 'https://repos.influxdata.com/influxdb.key'

                                                                   # ]]]
# .. envvar:: influxdb__upstream_apt_repository [[[
#
# The URL of the Influxdb upstream :command:`git` repository.
influxdb__upstream_apt_repository: 'deb https://repos.influxdata.com/ubuntu bionic stable'

                                                                   # ]]]
influxdb__deploy_type: '{{ "upstream"
                            if (ansible_distribution_release in
                              [ "wheezy", "jessie", "precise", "trusty", "xenial" ])
                            else "system" }}'
influxdb__dependent_upstream_enabled: False
# .. envvar:: influxdb__keyring__dependent_apt_keys [[[
#
# Configuration for the :ref:`debops.keyring` InfluxDB role.
influxdb__keyring__dependent_apt_keys:

  - id: '05CE15085FC09D18E99EFB22684A14CF2582E0C5'
    repo: '{{ influxdb__upstream_apt_repository }}'
    state: '{{ "present" if (influxdb__deploy_type == "upstream") else "absent" }}'
                                                                   # ]]]
                                                                   # ]]]
# Configuration for other Ansible roles [[[
# -----------------------------------------

# .. envvar:: influxdb__ferm__dependent_rules [[[
#
# Configuration for :ref:`debops.ferm` InfluxDB role.
influxdb__ferm__dependent_rules:

  - type: 'accept'
    dport: [ '8086' ]
    saddr: '{{ influxdb__allow }}'
    accept_any: False
    weight: '40'
    role: 'influxdb'

  - type: 'accept'
    dport: [ '8088' ]
    saddr: '{{ influxdb__allow }}'
    accept_any: False
    weight: '41'
    role: 'influxdb'


                                                                   # ]]]
# .. envvar:: influxdb__allow [[[
#
# List of IP addresses or CIDR subnets which will be allowed to connect to the
# InfluxDB server in :command:`ip(6)tables` and TCP wrappers. If it's empty, remote
# connections are not allowed.
influxdb__allow: [ '0.0.0.0/0' ]

                                                                   # ]]]
# .. envvar:: influxdb__hostname [[[
#
# Hostname added to the IQN to create Initiator Name.
influxdb__hostname: ''

                                                                   # ]]]
influxdb__database_username: 'john'
# influxdb_password: 's3cr3t'   aparent e o problema cu parola
influxdb__ip_address: '192.168.3.242'
influxdb__database_name: 'bechea'
# python__enabled: True
# Configuration for other Ansible roles [[[
# ----------------------------------------

# .. envvar:: influxdb__python__dependent_packages2 [[[
#
# Configuration for the :ref:`debops.python` InfluxDB role.
influxdb__python__dependent_packages2:

  - 'python-influxdb'

                                                                   # ]]]
# .. envvar:: influxdb__python__dependent_packages3 [[[
#
# Configuration for the :ref:`debops.python` InfluxDB role.
influxdb__python__dependent_packages3:

  - 'python3-influxdb'

                                                                   # ]]]
                                                                   # ]]]
