---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# debops.influxdb default variables [[[
# ====================================

# .. contents:: Sections
#    :local:
#
# .. include:: ../../../includes/global.rst


# InfluxDB server configuration [[[
# --------------------------------

# APT packages [[[
# ----------------

# .. envvar:: influxdb__base_packages [[[
#
# List of APT packages which are required by the InfluxDB application.
influxdb__base_packages: [ 'influxdb' ]

                                                                   # ]]]
# .. envvar:: influxdb__packages [[[
#
# List of APT packages which are required by the InfluxDB application.
influxdb__packages: [ 'influxdb-dev' ]

                                                                   # ]]]
# .. envvar:: influxdb__group_packages [[[
#
# List of APT packages to install on a group of hosts in Ansible inventory.
influxdb__group_packages: []

                                                                   # ]]]
# .. envvar:: influxdb__host_packages [[[
#
# List of APT packages to install on specific hosts in Ansible inventory.
influxdb__host_packages: []

                                                                   # ]]]
# .. envvar:: influxdb__dependent_packages [[[
#
# List of APT packages to install specified by other Ansible roles.
influxdb__dependent_packages: []
                                                                   # ]]]
                                                                   # ]]]
# .. envvar:: influxdb__upstream_apt_key [[[
#
# The OpenPGP key of the Influxdb upstream APT repository.
influxdb__upstream_apt_key: 'https://repos.influxdata.com/influxdb.key'

                                                                   # ]]]
# .. envvar:: influxdb__upstream_apt_repository [[[
#
# The URL of the Influxdb upstream :command:`git` repository.
influxdb__upstream_apt_repository: 'deb https://repos.influxdata.com/ubuntu bionic stable'

                                                                   # ]]]
influxdb__upstream_enabled: '{{ True
                                if (ansible_distribution_release in
                                    [ "jessie", "stretch", "trusty", "xenial" ])
                                else influxdb__dependent_upstream_enabled }}'

influxdb__dependent_upstream_enabled: False

# Configuration for other Ansible roles [[[
# -----------------------------------------

# .. envvar:: influxdb__ferm__dependent_rules [[[
#
# Configuration for :ref:`debops.ferm` Ansible role.
influxdb__ferm__dependent_rules:

  - type: 'accept'
    dport: [ '8086' ]
    saddr: '{{ influxdb_server__allow }}'
    accept_any: False
    weight: '40'
    role: 'influxdb'

  - type: 'accept'
    dport: [ '8088' ]
    saddr: '{{ influxdb_server__allow }}'
    accept_any: False
    weight: '41'
    role: 'influxdb'


                                                                   # ]]]
# .. envvar:: influxdb_server__allow [[[
#
# List of IP addresses or CIDR subnets which will be allowed to connect to the
# InfluxDB server in :command:`ip(6)tables` and TCP wrappers. If it's empty, remote
# connections are not allowed.
influxdb_server__allow: [ '0.0.0.0/0' ]

                                                                   # ]]]
                                                                   # ]]]
# .. envvar:: influxdb_apt_repository_key_url [[[
#
# The key of the upstream InfluxDB APT repository.
# influxdb_apt_repository_key_url: 'https://repos.influxdata.com/influxdb.key'

                                                                   # ]]]
# .. envvar:: influxdb__upstream_apt_repository [[[
#
# The APT repository URI of the upstream InfluxDB repository.
# influxdb__upstream_apt_repository: 'deb https://repos.influxdata.com/ubuntu bionic stable'

                                                                   # ]]]
# influxdb_release: '{{ ansible_local.core.distribution_release
#                     if (ansible_local|d() and ansible_local.core|d() and
#                         ansible_local.core.distribution_release|d())
#                     else ansible_distribution_release }}'
influxdb_hostname: 'varnish-1'
influxdb_username: 'john'
influxdb_password: 's3cr3t'
influxdb_ip_address: '192.168.3.218'
influxdb_database_name: 'bechea'



python__enabled: True

# Configuration for other Ansible roles [[[
# ----------------------------------------

# .. envvar:: influxdb__python__dependent_packages2 [[[
#
# Configuration for the :ref:`debops.python` Ansible role.
influxdb__python__dependent_packages2:

  - 'python-influxdb'

                                                                   # ]]]
# .. envvar:: influxdb__python__dependent_packages3 [[[
#
# Configuration for the :ref:`debops.python` Ansible role.
influxdb__python__dependent_packages3:

  - 'python3-influxdb'

                                                                   # ]]]
                                                                   # ]]]
