---

- name: Install Influxdb requested packages
  package:
    name: '{{ item }}'
    state: 'present'
  with_flattened:
    - '{{ influxdb__base_packages }}'
    - '{{ influxdb__packages }}'
    - '{{ influxdb__host_packages }}'
    - '{{ influxdb__group_packages }}'
    - '{{ influxdb__dependent_packages }}'
  register: influxdb__register_install
  until: influxdb__register_install is succeeded
  notify: [ 'Restart influxdb' ]

- name: Install required Python modules
  pip:
    name: '{{ item }}'
    state: 'latest'
  with_items: '{{ influxdb__pip_packages }}'
  register: influxdb__register_pip_install
  until: influxdb__register_pip_install is succeeded
  when: influxdb__pip_packages|d()

- name: Divert the original influxdb configuration file
  command: dpkg-divert --quiet --local --divert /etc/influxdb/influxdb.conf.dpkg-divert --rename /etc/influxdb/influxdb.conf
  args:
    creates: '/etc/influxdb/influxdb.conf.dpkg-divert'

- name: Configure main influxdb config file
  template:
    src: 'influxdb.conf.j2'
    dest: '/etc/influxdb/influxdb.conf'
    owner: 'root'
    group: 'adm'
    mode: '0644'

- name: Drop database
  influxdb_database:
    hostname: '{{ item.hostname | d(item.name) }}'
    database_name: '{{ item.database_name }}'
    state: 'absent'
  with_flattened: '{{ influxdb__databases + influxdb__dependent_databases }}'
  when: ((item.database_name|d(False) or item.hostname|d(False)) and
         (item.state is defined and item.state == 'absent'))

- name: Create database
  influxdb_database:
    hostname: '{{ item.hostname | d(item.name) }}'
    database_name: '{{ item.database_name }}'
    state: 'present'
    encoding: '{{ item.encoding | d(omit) }}'
    collation: '{{ item.collation | d(omit) }}'
  with_flattened: '{{ influxdb__databases + influxdb__dependent_databases }}'
  when: ((item.database_name|d(False) or item.hostname|d(False)) and
         (item.state is undefined or item.state != 'absent'))
  register: influxdb__register_database_status

- name: Drop user
  influxdb_user:
    user_name: '{{ item.user_name | d(item.name) }}'
    # user_password: '{{ item.user_password }}'
    hostname: '{{ item.hostname | default(influxdb__hostname) }}'
    state: 'absent'
  with_flattened: '{{ influxdb__users + influxdb__dependent_users }}'
  when: ((item.user_name|d(False)) and
         (item.state is defined and item.state == "absent"))

- name: Create user
  influxdb_user:
    user_name: '{{ item.user_name | d(item.name) }}'
    user_password: '{{ item.user_password | default(lookup("password",
                  secret + "/influxdb/" +
                  "/credentials/" + item.user_name | d(False) + "/password " +
                  "length=" + influxdb__password_length)) }}'
    # admin: '{{ item.admin | d(omit) }}'
    grants: '{{ item.grants | d(omit) }}'
    hostname: '{{ item.hostname | default(influxdb__hostname) }}'
    login_username: '{{ item.login_username | d(omit) }}'
    login_password: '{{ item.login_password | d(omit) }}'
    state: 'present'
  with_flattened: '{{ influxdb__users + influxdb__dependent_users }}'
  register: influxdb__register_create_users
  when: ((item.user_name|d(False) or item.user_password|d(False) or item.login_username|d(False) or item.login_password|d(False)) and
         (item.state is undefined or item.state != "absent"))

- name: Make sure that Ansible local facts directory exists
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    mode: '0755'

- name: Save telegraf local facts
  template:
    src: 'etc/ansible/facts.d/influxdb.fact.j2'
    dest: '/etc/ansible/facts.d/influxdb.fact'
    mode: '0755'
  register: influxdb__register_facts

- name: Update Ansible facts if they were modified
  action: setup
  when: influxdb__register_facts is changed
