---

- name: Install Influxdb requested packages
  package:
    name: '{{ item }}'
    state: 'present'
  with_flattened:
    - '{{ influxdb__base_packages }}'
    - '{{ influxdb__packages }}'
    - '{{ influxdb__host_packages }}'
    - '{{ influxdb__group_packages }}'
    - '{{ influxdb__dependent_packages }}'
  register: influxdb__register_install
  until: influxdb__register_install is succeeded
  notify: [ 'Reload influxdb' ]

- name: Create an admin user on a remote host using custom login credentials
  influxdb_user:
    user_name: john
    user_password: s3cr3t
    admin: yes
    hostname: "{{ influxdb__hostname }}"
    # login_username: "{{ influxdb_username }}"
    # login_password: "{{ influxdb_password }}"

- name: Create database
  influxdb_database:
    hostname: "{{ influxdb__ip_address }}"
    username: "{{ influxdb__database_username }}"
    # password: "{{ influxdb_password }}"
    database_name: "{{ influxdb__database_name }}"
