---

dependencies: []

galaxy_info:

  author: 'Maciej Delmanowski'
  description: 'Prepare a dpkg cleanup hook executed on package removal'
  company: 'DebOps'
  license: 'GPL-3.0-only'
  min_ansible_version: '2.9.0'
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
        - bullseye
  galaxy_tags:
    - cleanup
    - system
    - dpkg
    - apt
