---

- name: Add Influxdata APT key
  apt_key:
    url: '{{ influxdata__upstream_key }}'
    state: 'present'
  when: "{{ influxdata__upstream_enabled }}"

- name: Add Influxdata APT repository
  apt_repository:
    repo: '{{ influxdata__upstream_repo }}'
    state: 'present'
    update_cache: True
    mode: '0644'
  when: "{{ influxdata__upstream_enabled }}"

- name: Install Influxdata requested packages
  package:
    name: '{{ item }}'
    state: 'present'
    update_cache: True
    force: yes
  with_flattened:
    - '{{ influxdata__base_packages }}'
    - '{{ influxdata__packages }}'
    - '{{ influxdata__host_packages }}'
    - '{{ influxdata__group_packages }}'
    - '{{ influxdata__dependent_packages }}'
  register: influxdata__register_install
  until: influxdata__register_install is succeeded
