---

- name: Manage Grafana
  hosts: [ 'debops_service_grafana', 'debops_grafana' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.etc_services
      tags: [ 'role::etc_services', 'skip::etc_services' ]
      etc_services__dependent_list:
        - '{{ grafana__etc_services__dependent_list }}'

    - role: debops.grafana
      tags: [ 'role::grafana', 'skip::grafana' ]

    - role: debops.ferm
      tags: [ 'role::ferm', 'skip::ferm' ]
      ferm__dependent_rules:
        - '{{ grafana__ferm__dependent_rules }}'
