---

- name: Install Telegraf requested packages
  package:
    name: '{{ item }}'
    state: 'present'
    # update_cache: True
    force: yes
  with_flattened:
    - '{{ telegraf__base_packages }}'
    - '{{ telegraf__packages }}'
  register: telegraf__register_install
  until: telegraf__register_install is succeeded

- name: Divert the original telegraf configuration file
  command: dpkg-divert --quiet --local --divert /etc/telegraf/telegraf.conf.dpkg-divert --rename /etc/telegraf/telegraf.conf
  args:
    creates: '/etc/telegraf/telegraf.conf.dpkg-divert'

- name: Configure main telegraf config file
  template:
    src: 'telegraf.conf.j2'
    dest: '/etc/telegraf/telegraf.conf'
    owner: 'root'
    group: 'adm'
    mode: '0644'
  notify: [ 'Reload telegraf' ]

- name: Make sure that Ansible local facts directory exists
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    mode: '0755'

- name: Save telegraf local facts
  template:
    src: 'etc/ansible/facts.d/telegraf.fact.j2'
    dest: '/etc/ansible/facts.d/telegraf.fact'
    mode: '0755'
  register: telegraf__register_facts

- name: Update Ansible facts if they were modified
  action: setup
  when: telegraf__register_facts is changed
