---
- name: Install requested packages
  package:
    name: '{{ item }}'
    state: 'present'
    # update_cache: True
    install_recommends: True
  with_flattened:
    - '{{ telegraf__base_packages }}'
    - '{{ telegraf__packages }}'

- name: Rename the original file telegraf.conf to telegraf.conf.default
  command: mv /etc/telegraf/telegraf.conf /etc/telegraf/telegraf.conf.default

- name: Create a new file inside /etc/telegraf named telegraf.conf
  command: touch /etc/telegraf/telegraf.conf

- name: Apply the template telegraf.conf.j2 to /etc/telegraf/
  template: src=telegraf.conf.j2 dest=/etc/telegraf/telegraf.conf

- name: Generate conf using telegraf command
  command: telegraf config -input-filter cpu:mem:disk:swap:system -output-filter influxdb > telegraf.conf
