---

dependencies:

  - role: debops.ansible_plugins

galaxy_info:

  role_name: 'telegraf'
  author: 'Bechea Leonardo'
  description: 'Configure Telegraf service'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'
  platforms:
    - name: Debian
      versions:
        - bionic
        - wheezy
        - jessie
  galaxy_tags:
    - telegraf
