---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# debops.influxdb default variables [[[
# ====================================

# .. contents:: Sections
#    :local:
#
# .. include:: ../../../includes/global.rst


# Telegraf server configuration [[[
# --------------------------------


# .. envvar:: telegraf__upstream_apt_key [[[
#
# The OpenPGP key of the Telegraf upstream APT repository.
telegraf__upstream_apt_key: 'https://repos.influxdata.com/influxdb.key'

                                                                   # ]]]
# .. envvar:: telegraf__upstream_apt_repository [[[
#
# The URL of the Telegraf upstream :command:`git` repository.
telegraf__upstream_apt_repository: 'deb https://repos.influxdata.com/ubuntu bionic stable'

                                                                   # ]]]
# Installation, APT packages [[[
# ------------------------------

# .. envvar:: telegraf__deploy_type [[[
#
# Select how Telegraf should be installed by the role:
#
# - ``system``: install Telegraf using current OS packages, possibly from the
#               backports repository.
#
# - ``upstream``: install Telegraf from the upstream APT repository on
#                 Launchpad (PPA, usable on Debian as well).
#
# - ``bootstrap``: install APT packages required for Telegraf and build a local
#                  ``.deb`` package using the upstream GitHub repository.
#
telegraf__deploy_type: "upstream"

                                                                   # ]]]
# APT packages [[[
# ----------------

# .. envvar:: telegraf__base_packages [[[
#
# List of APT packages which are required by the Telegraf application.
telegraf__base_packages: [ 'telegraf' ]

                                                                   # ]]]
# .. envvar:: telegraf__packages [[[
#
# List of APT packages which are required by the Telegraf application.
telegraf__packages: [ 'apt-transport-https' ]

                                                                   # ]]]
# Upstream telegraf installation [[[
# ------------------------------

# .. envvar:: telegraf__upstream_enabled [[[
#
# Enable or disable installation of the :command:`yadm` script from upstream
# :command:`git` repository.
telegraf__dependent_upstream_enabled: False

                                                                   # ]]]
# .. envvar:: telegraf__keyring__dependent_apt_keys [[[
#
# Configuration for the :ref:`debops.keyring` Ansible role.
telegraf__keyring__dependent_apt_keys:

  - id: '05CE15085FC09D18E99EFB22684A14CF2582E0C5'
    # url: '{{ telegraf__upstream_apt_key }}'
    repo: '{{ telegraf__upstream_apt_repository }}'
    state: '{{ "present" if (telegraf__deploy_type == "upstream") else "absent" }}'
                                                                   # ]]]
                                                                   # ]]]
# .. envvar:: telegraf__allow [[[
#
# List of IP addresses or CIDR subnets which will be allowed to connect to the
# Telegraf server in :command:`ip(6)tables` and TCP wrappers. If it's empty, remote
# connections are not allowed.
telegraf__allow: [ '0.0.0.0/0' ]

                                                                   # ]]]
# Telegraf configuration file [[[
# ------------------------------------

# The variables below define the contents of the
# :file:`/etc/telegraf/telegraf.conf` configuration file.
# See :ref:`telegraf__ref_configuration` for the details and configuration
# syntax.

# .. envvar:: telegraf__default_configuration [[[
#
# The default configuration options which should be present in the main
# configuration file.
telegraf__default_configuration:

  - name: global_tags
    options:
      - dc: '"us-east-1"'
        rack: '"1a"'
        user: '"$USER"'

  - name: 'agent'
    options:
      - hostname: '"$hostname"'
      - flush_interval: '"15s"'
      - interval: '"15s"'

  - name: inputs.cpu
    options:
      - percpu: 'true'
        totalcpu: 'true'
        collect_cpu_time: 'false'
        report_active: 'false'

  - name: inputs.disk
    options:
      - fielddrop: '[ "inodes" ]'
      - mount_points: '[ "/" ]'
      - ignore_fs: '[ "tmpfs", "devtmpfs", "devfs" ]'

  - name: inputs.net
    options:
      - interfaces: '[ "eth0" ]'
      - fielddrop: '[ "icmp*", "ip*", "tcp*", "udp*" ]'

  # Get the number of processes and group them by status
  - name: inputs.processes
    options: []

  - name: inputs.netstat
    options: []

  - name: inputs.processes
    options: []

  # Get kernel statistics from /proc/stat
  - name: inputs.kernel
    options: []

  # Read metrics about disk IO by device
  - name: inputs.diskio
    options: []

  - name: inputs.mem
    options: []

  - name: inputs.swap
    options: []

  - name: inputs.system
    options: []


  - name: outputs.influxdb
    options:
       - database: '"bechea"'
       - password: '"s3cr3t"'
       - urls: '[ "http://192.168.3.242:8086" ]'
       - username: '"john"'

                                                                   # ]]]
# .. envvar:: telegraf__configuration [[[
#
# List of configuration options defined on all hosts in the Ansible inventory.
telegraf__configuration: []

                                                                   # ]]]
# .. envvar:: telegraf__combined_configuration [[[
#
# Actual list of Telegraf configuration options passed to the
# configuration template. This list defines the order in which the options from
# different variables are processed.
telegraf__combined_configuration: '{{ telegraf__default_configuration + telegraf__configuration }}'

                                                                   # ]]]
