---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# debops.grafana default variables [[[
# ====================================

# .. contents:: Sections
#    :local:
#
# .. include:: ../../../includes/global.rst


# Grafana server configuration [[[
# --------------------------------

# APT packages [[[
# ----------------

# .. envvar:: grafana__base_packages [[[
#
# List of APT packages which are required by the Grafana application.
grafana__base_packages: [ 'grafana' ]

                                                                   # ]]]
# .. envvar:: grafana__packages [[[
#
# List of APT packages which are required by the Grafana application.
grafana__packages: [ 'software-properties-common', 'apt-transport-https' ]

                                                                   # ]]]
# .. envvar:: grafana_server__allow [[[
#
# List of IP addresses or CIDR subnets which will be allowed to connect to the
# Grafana server in :command:`ip(6)tables` and TCP wrappers. If it's empty, remote
# connections are not allowed.
grafana_server__allow: [ '0.0.0.0/0' ]

                                                                   # ]]]
                                                                   # ]]]
# .. envvar:: grafana_apt_repository_key_url [[[
#
# The GPG key of the upstream Grafana APT repository.
grafana_apt_repository_key_url: 'https://packages.grafana.com/gpg.key'

                                                                   # ]]]
# .. envvar:: grafanab__upstream_apt_repository [[[
#
# The APT repository URI of the upstream Grafana repository.
grafana__upstream_apt_repository: 'deb https://packages.grafana.com/oss/deb stable main'

                                                                   # ]]]
# Configuration for other Ansible roles [[[
# -----------------------------------------

# .. envvar:: grafana__ferm__dependent_rules [[[
#
# Configuration for :ref:`debops.ferm` Ansible role.
grafana__ferm__dependent_rules:

  - type: 'accept'
    dport: [ '3000' ]
    saddr: '{{ grafana_server__allow }}'
    accept_any: False
    weight: '40'
    role: 'grafana'


                                                                   # ]]]





grafana_release: '{{ ansible_local.core.distribution_release
                    if (ansible_local|d() and ansible_local.core|d() and
                        ansible_local.core.distribution_release|d())
                    else ansible_distribution_release }}'


