---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# debops.grafana default variables [[[
# ====================================

# .. contents:: Sections
#    :local:
#
# .. include:: ../../../includes/global.rst


# Grafana server configuration [[[
# --------------------------------

# .. envvar:: grafana_apt_repository_key_url [[[
#
# The GPG key of the upstream Grafana APT repository.
grafana_apt_repository_key_url: 'https://packages.grafana.com/gpg.key'

                                                                   # ]]]
# .. envvar:: grafana__upstream_apt_repository [[[
#
# The APT repository URI of the upstream Grafana repository.
grafana__upstream_apt_repository: 'deb https://packages.grafana.com/oss/deb stable main'

                                                                   # ]]]
# APT packages [[[
# ----------------

# .. envvar:: grafana__base_packages [[[
#
# List of APT packages which are required by the Grafana application.
grafana__base_packages: [ 'grafana' ]

                                                                   # ]]]
# .. envvar:: grafana__packages [[[
#
# List of APT packages to install on all hosts in Ansible inventory.
grafana__packages: [ 'software-properties-common', 'apt-transport-https' ]

                                                                   # ]]]
# .. envvar:: grafana_server__allow [[[
#
# List of IP addresses or CIDR subnets which will be allowed to connect to the
# Grafana server in :command:`ip(6)tables` and TCP wrappers. If it's empty, remote
# connections are not allowed.
grafana_allow: [ '0.0.0.0/0' ]

                                                                   # ]]]
# .. envvar:: grafana__port [[[
#
# Port number on which this Grafana server listens on.
grafana__port: '3000'

                                                                   # ]]]
# Configuration for other Ansible roles [[[
# -----------------------------------------

# .. envvar:: grafana__ferm__dependent_rules [[[
#
# Configuration for :ref:`debops.ferm` Ansible role.
grafana__ferm__dependent_rules:

  - type: 'accept'
    dport: [ 'grafana' ]
    saddr: '{{ grafana_allow }}'
    accept_any: False
    weight: '40'
    role: 'grafana'

                                                                   # ]]]
# .. envvar:: grafana__etc_services__dependent_list [[[
#
# Configuration for the :ref:`debops.etc_services` Ansible role.
grafana__etc_services__dependent_list:

  - name: 'grafana'
    port: '{{ grafana__port }}'

                                                                   # ]]]
